globalThis.STORE_MASTER_SEED = {
  version: "2026-07-13",
  currency: "BRL",
  locale: "pt-BR",
  source: {
    type: "manual-transcription-from-screenshots",
    description: "Tabela completa da loja - lote inicial de capturas enviadas pelo usuario.",
    status: "partial-seed",
  },
  categories: [
    {
      id: "impressao-digital",
      label: "Impressao digital",
      status: "ready",
      products: [
        {
          id: "roland-adesivo-branco-e-lona",
          label: "Adesivo branco e lona",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 30,
          minimumReference: "A3",
          tiers: [
            { upTo: 2, price: 90 },
            { min: 2, upTo: 4, price: 85 },
            { min: 4, upTo: 6, price: 80 },
            { min: 6, upTo: 10, price: 75 },
            { min: 10, price: 65 },
          ],
          notes: ["Roland VS 640"],
          canCombineWith: ["acabamentos-m2", "laminacao", "criacao"],
        },
        {
          id: "sid-triton-adesivo-branco-lona",
          label: "Adesivo branco lona",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 25,
          tiers: [
            { upTo: 2, price: 70 },
            { min: 2, upTo: 4, price: 65 },
            { min: 4, upTo: 6, price: 63 },
            { min: 6, upTo: 10, price: 60 },
            { min: 10, price: 58 },
          ],
          notes: ["SID Triton 210", "Para banner pequeno cobrar acabamento adicional de R$ 5,00 quando aplicavel."],
          canCombineWith: ["acabamentos-m2", "laminacao", "criacao"],
        },
        {
          id: "perfurado",
          label: "Adesivo perfurado",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 45,
          minimumReference: "A2",
          tiers: [
            { upTo: 5, price: 88 },
            { min: 5, price: 75 },
          ],
          canCombineWith: ["acabamentos-m2", "laminacao"],
        },
        {
          id: "ps-1mm",
          label: "Chapa PS 1 mm",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 39,
          minimumReference: "A3",
          tiers: [
            { upTo: 1, price: 176 },
            { min: 1, upTo: 2, price: 164 },
            { min: 2, upTo: 4, price: 152 },
            { min: 4, upTo: 10, price: 146 },
            { min: 10, price: 144 },
          ],
          canCombineWith: ["acabamentos-m2", "criacao"],
        },
        {
          id: "ps-2mm",
          label: "Chapa PS 2 mm",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 39,
          minimumReference: "A3",
          tiers: [
            { upTo: 1, price: 200 },
            { min: 1, upTo: 2, price: 194 },
            { min: 2, upTo: 4, price: 188 },
            { min: 4, upTo: 10, price: 182 },
            { min: 10, price: 178 },
          ],
          canCombineWith: ["acabamentos-m2", "criacao"],
        },
        {
          id: "magneto-automotivo-20x60",
          label: "Magneto automotivo 20x60 cm",
          pricingModel: "fixed",
          unit: "un",
          price: 55,
          canCombineWith: ["criacao"],
        },
        {
          id: "magneto-automotivo-metro-linear",
          label: "Magneto automotivo metro linear (altura 60 cm)",
          pricingModel: "linear_meter",
          unit: "m",
          price: 164,
          canCombineWith: ["criacao"],
        },
        {
          id: "papel-65g-metro-linear",
          label: "Papel 65g",
          pricingModel: "linear_meter_with_minimum",
          unit: "m",
          minimumQuantity: 1,
          price: 34,
          notes: ["Largura 1,4 m"],
        },
        {
          id: "laminacao-transparente-ou-jateado",
          label: "Laminacao transparente ou jateado",
          pricingModel: "area_with_minimum",
          unit: "m2",
          price: 30,
          minimumCharge: 5,
          canCombineWith: ["impressao-digital", "m2"],
        },
      ],
    },
    {
      id: "materiais-flexiveis",
      label: "Materiais flexiveis e especiais",
      status: "ready",
      products: [
        {
          id: "dtf-textil-58cm",
          label: "DTF textil 58 cm",
          pricingModel: "progressive-length",
          unit: "cm",
          minimumCharge: 35,
          rules: [
            { description: "10 cm minimo", price: 35 },
            { description: "cada 10 cm adicionais", incrementPrice: 20, incrementUnit: 10 },
            { description: "50 cm", price: 60 },
            { description: "1 m", price: 100 },
          ],
          notes: ["Entregue sem acabamento."],
        },
        {
          id: "canvas-124",
          label: "Canvas largura 1,24 m",
          pricingModel: "linear_meter_with_minimum",
          unit: "m",
          minimumCharge: 45,
          minimumReference: "40 cm",
          price: 110,
        },
        {
          id: "couche-210g-95cm",
          label: "Couche 210g largura 95 cm",
          pricingModel: "linear_meter_with_minimum_quantity",
          unit: "m",
          minimumQuantity: 1,
          price: 39,
        },
        {
          id: "couche-170g-95cm",
          label: "Couche 170g largura 95 cm",
          pricingModel: "linear_meter_with_minimum_quantity",
          unit: "m",
          minimumQuantity: 1,
          price: 34,
        },
        {
          id: "adesivo-troca-de-oleo",
          label: "Adesivo troca de oleo",
          pricingModel: "area_with_minimum_quantity",
          unit: "m2",
          minimumQuantity: 500,
          price: 221,
        },
      ],
    },
    {
      id: "copias-e-coloridos",
      label: "Copias e impressos coloridos",
      status: "mostly-ready",
      products: [
        {
          id: "papel-75g-colorido",
          label: "Copia ou impressao colorida - Papel 75g",
          pricingModel: "sheet_tiers_by_size",
          tiersByVariant: [
            {
              variant: "A4",
              tiers: [
                { min: 1, upTo: 5, price: 4 },
                { min: 6, upTo: 10, price: 3.5 },
                { min: 11, upTo: 50, price: 2 },
                { min: 51, upTo: 100, price: 1.9 },
                { min: 101, upTo: 300, price: 1.75 },
                { min: 300, price: 1.5 },
              ],
            },
            {
              variant: "A3",
              tiers: [
                { min: 1, upTo: 5, price: 7 },
                { min: 6, upTo: 10, price: 5 },
                { min: 11, upTo: 50, price: 3.95 },
                { min: 51, upTo: 100, price: 3.75 },
                { min: 101, upTo: 300, price: 3.5 },
                { min: 300, price: 3.05 },
              ],
            },
          ],
          canCombineWith: ["plastificacao", "encadernacoes", "criacao"],
        },
        {
          id: "papel-couche-ou-offset-170g-colorido",
          label: "Copia ou impressao colorida - Papel couche ou offset 170g",
          pricingModel: "sheet_tiers_by_size",
          tiersByVariant: [
            {
              variant: "A4",
              tiers: [
                { min: 1, upTo: 5, price: 5 },
                { min: 6, upTo: 10, price: 4 },
                { min: 11, upTo: 50, price: 2.75 },
                { min: 51, upTo: 100, price: 2.4 },
                { min: 101, upTo: 300, price: 2.2 },
                { min: 300, price: 2 },
              ],
            },
            {
              variant: "A3",
              tiers: [
                { min: 1, upTo: 5, price: 8 },
                { min: 6, upTo: 10, price: 7 },
                { min: 11, upTo: 30, price: 5.5 },
                { min: 31, upTo: 100, price: 4.8 },
                { min: 101, upTo: 300, price: 4.4 },
                { min: 300, price: 3.95 },
              ],
            },
          ],
          canCombineWith: ["plastificacao", "encadernacoes", "criacao"],
        },
        {
          id: "papel-couche-250g-colorido",
          label: "Copia ou impressao colorida - Papel couche 250g",
          pricingModel: "sheet_tiers_by_size",
          tiersByVariant: [
            {
              variant: "A4",
              tiers: [
                { min: 1, upTo: 5, price: 5 },
                { min: 6, upTo: 10, price: 4 },
                { min: 11, upTo: 50, price: 3.2 },
                { min: 51, upTo: 100, price: 2.85 },
                { min: 101, upTo: 300, price: 2.75 },
                { min: 300, price: 2.45 },
              ],
            },
            {
              variant: "A3",
              tiers: [
                { min: 1, upTo: 5, price: 8 },
                { min: 6, upTo: 10, price: 7 },
                { min: 11, upTo: 30, price: 5.95 },
                { min: 31, upTo: 100, price: 5.4 },
                { min: 101, upTo: 300, price: 5.15 },
                { min: 300, price: 4.8 },
              ],
            },
          ],
          canCombineWith: ["plastificacao", "encadernacoes", "criacao"],
        },
        {
          id: "papel-couche-300g-metalizados-colorido",
          label: "Copia ou impressao colorida - Papel couche 300g e metalizados",
          pricingModel: "sheet_tiers_by_size",
          tiersByVariant: [
            {
              variant: "A4",
              tiers: [
                { min: 1, upTo: 5, price: 9 },
                { min: 6, upTo: 10, price: 8 },
                { min: 11, upTo: 50, price: 5.05 },
                { min: 51, upTo: 100, price: 4.9 },
                { min: 101, upTo: 300, price: 4.4 },
              ],
            },
            {
              variant: "A3",
              tiers: [
                { min: 1, upTo: 5, price: 14 },
                { min: 6, upTo: 10, price: 13 },
                { min: 11, upTo: 30, price: 9.2 },
                { min: 31, upTo: 100, price: 8.55 },
                { min: 101, upTo: 300, price: 7.85 },
              ],
            },
          ],
          notes: ["Faixas acima de 300 nao ficaram totalmente legiveis no print e devem ser conferidas depois."],
          canCombineWith: ["plastificacao", "encadernacoes", "criacao"],
        },
      ],
    },
    {
      id: "xerox-e-riso",
      label: "Xerox e impressao riso",
      status: "partial",
      products: [
        {
          id: "xerox-a4-preto-branco",
          label: "Xerox A4 preto e branco",
          pricingModel: "unit_tiers",
          tiers: [
            { exact: 1, totalPrice: 2 },
            { exact: 2, totalPrice: 3 },
            { min: 3, upTo: 5, price: 1 },
            { min: 6, upTo: 10, price: 0.6 },
            { min: 11, upTo: 50, price: 0.3 },
            { min: 51, upTo: 99, price: 0.2 },
            { min: 100, price: 0.18 },
          ],
          notes: [
            "Acima de 1.000 frente e verso: R$ 0,13 por impressao.",
            "Acima de 10.000 frente e verso: R$ 0,12 por impressao.",
            "No frente e verso, o verso conta 2 impressoes.",
          ],
        },
        {
          id: "xerox-a3-preto-branco",
          label: "Xerox A3 preto e branco",
          pricingModel: "unit_tiers",
          tiers: [
            { exact: 1, price: 2.5 },
            { min: 2, upTo: 10, price: 1.8 },
            { min: 11, upTo: 50, price: 0.8 },
            { min: 51, upTo: 100, price: 0.55 },
            { min: 101, upTo: 200, price: 0.5 },
            { min: 200, price: 0.45 },
          ],
        },
        {
          id: "ampliacao-a4",
          label: "Ampliacao A4",
          pricingModel: "fixed",
          unit: "un",
          price: 2.5,
        },
        {
          id: "impressao-a3",
          label: "Impressao A3",
          pricingModel: "fixed",
          unit: "un",
          price: 3.5,
        },
        {
          id: "riso-a4-papel-75g",
          label: "Impressao riso A4 papel 75g",
          pricingModel: "unit_tiers",
          tiers: [
            { min: 1, upTo: 10, price: 2 },
            { min: 11, upTo: 20, price: 1.5 },
            { min: 21, upTo: 50, price: 1 },
            { min: 51, upTo: 100, price: 0.6 },
            { min: 100, upTo: 500, price: 0.4 },
            { min: 501, upTo: 1000, price: 0.3 },
            { min: 1000, upTo: 5000, price: 0.25 },
            { min: 5000, price: 0.2 },
          ],
          notes: ["Para impressao acima de 100 unidades, valores para material sem charrão.", "Blocos coloridos com impressao riso acrescentam 40% no bloco preto e branco."],
        },
      ],
    },
    {
      id: "offset-folha",
      label: "Papel offset e especiais em folha",
      status: "ready",
      products: [
        {
          id: "offset-120g-preto-branco",
          label: "Papel offset 120g - preto e branco",
          pricingModel: "sheet_tiers_variants",
          tiersByVariant: [
            {
              variant: "A4 so frente",
              tiers: [
                { min: 1, upTo: 10, price: 2 },
                { min: 11, upTo: 50, price: 0.75 },
                { min: 51, upTo: 100, price: 0.7 },
                { min: 101, upTo: 300, price: 0.65 },
                { min: 300, price: 0.6 },
              ],
            },
            {
              variant: "A4 frente e verso",
              tiers: [
                { min: 1, upTo: 50, price: 2.5 },
                { min: 51, upTo: 100, price: 1.3 },
                { min: 101, upTo: 300, price: 1.1 },
                { min: 300, price: 1 },
              ],
            },
            {
              variant: "A3 so frente",
              tiers: [
                { min: 1, upTo: 50, price: 2 },
                { min: 51, upTo: 100, price: 1.8 },
                { min: 101, upTo: 300, price: 1.43 },
                { min: 300, price: 1.36 },
              ],
            },
            {
              variant: "A3 frente e verso",
              tiers: [
                { min: 1, upTo: 50, price: 2.1 },
                { min: 51, upTo: 100, price: 1.95 },
                { min: 101, upTo: 300, price: 1.75 },
                { min: 300, price: 1.7 },
              ],
            },
          ],
        },
        {
          id: "offset-120g-colorido",
          label: "Papel offset 120g - colorido",
          pricingModel: "sheet_tiers_variants",
          tiersByVariant: [
            {
              variant: "A4",
              tiers: [
                { min: 1, upTo: 5, price: 5 },
                { min: 6, upTo: 10, price: 4 },
                { min: 11, upTo: 50, price: 2.45 },
                { min: 51, upTo: 100, price: 2.3 },
                { min: 101, upTo: 300, price: 2.2 },
                { min: 300, price: 1.95 },
              ],
            },
            {
              variant: "A3",
              tiers: [
                { min: 1, upTo: 5, price: 8 },
                { min: 6, upTo: 10, price: 7 },
                { min: 11, upTo: 50, price: 4.8 },
                { min: 51, upTo: 100, price: 4.55 },
                { min: 101, upTo: 300, price: 4.15 },
                { min: 300, price: 3.75 },
              ],
            },
          ],
        },
        {
          id: "offset-170g-preto-branco",
          label: "Papel offset 170g - preto e branco",
          pricingModel: "sheet_tiers_variants",
          tiersByVariant: [
            {
              variant: "A4 so frente",
              tiers: [
                { min: 1, upTo: 10, price: 2 },
                { min: 11, upTo: 50, price: 1 },
                { min: 51, upTo: 100, price: 0.8 },
                { min: 101, upTo: 300, price: 0.85 },
                { min: 300, price: 0.7 },
              ],
            },
            {
              variant: "A4 frente e verso",
              tiers: [
                { min: 1, upTo: 10, price: 3.5 },
                { min: 11, upTo: 50, price: 1.8 },
                { min: 51, upTo: 100, price: 1.3 },
                { min: 101, upTo: 300, price: 0.85 },
              ],
            },
            {
              variant: "A3 so frente",
              tiers: [
                { min: 1, upTo: 50, price: 2.5 },
                { min: 51, upTo: 100, price: 2 },
                { min: 101, upTo: 300, price: 1.65 },
                { min: 300, price: 1.5 },
              ],
            },
            {
              variant: "A3 frente e verso",
              tiers: [
                { min: 1, upTo: 50, price: 4 },
                { min: 51, upTo: 100, price: 3.5 },
                { min: 101, upTo: 300, price: 1.9 },
                { min: 300, price: 1.75 },
              ],
            },
          ],
        },
        {
          id: "papel-adesivo-a4-com-corte",
          label: "Papel adesivo A4 com corte",
          pricingModel: "fixed_brackets",
          unit: "folha",
          brackets: [
            { description: "ate 100 na folha", price: 8 },
            { description: "de 100 a 150 na folha", price: 14 },
            { description: "acima de 150 na folha", price: 19 },
          ],
          notes: ["A3 cobrar o dobro do A4."],
        },
        {
          id: "papel-adesivo-a4-sem-corte",
          label: "Papel adesivo A4 sem corte",
          pricingModel: "sheet_tiers",
          tiers: [
            { min: 1, upTo: 5, price: 5 },
            { min: 6, upTo: 10, price: 4 },
            { min: 11, upTo: 50, price: 3.65 },
            { min: 51, upTo: 100, price: 3.3 },
            { min: 101, upTo: 300, price: 3.15 },
            { min: 300, price: 3 },
          ],
          notes: ["A3 cobrar o dobro do A4."],
        },
        {
          id: "papel-kraft-80g-a4",
          label: "Papel kraft 80g A4",
          pricingModel: "sheet_tiers",
          tiers: [
            { min: 1, upTo: 50, price: 2.2 },
            { min: 51, upTo: 100, price: 2.1 },
            { min: 101, upTo: 300, price: 2 },
            { min: 300, price: 1.7 },
          ],
        },
        {
          id: "papel-kraft-110g-a4",
          label: "Papel kraft 110g A4",
          pricingModel: "sheet_tiers",
          tiers: [
            { min: 1, upTo: 50, price: 2.55 },
            { min: 51, upTo: 100, price: 2.45 },
            { min: 101, upTo: 300, price: 2.3 },
            { min: 300, price: 2.1 },
          ],
        },
        {
          id: "papel-kraft-170g-a4",
          label: "Papel kraft 170g A4",
          pricingModel: "sheet_tiers",
          tiers: [
            { min: 1, upTo: 50, price: 3.05 },
            { min: 51, upTo: 100, price: 2.7 },
            { min: 101, upTo: 300, price: 2.45 },
            { min: 300, price: 2.2 },
          ],
        },
        {
          id: "adesivo-vinil-laser-sem-corte",
          label: "Adesivo vinil com impressao laser - somente impressao",
          pricingModel: "sheet_tiers",
          tiers: [
            { exact: 1, price: 15 },
            { min: 2, upTo: 5, price: 12 },
            { min: 5, upTo: 10, price: 11 },
            { min: 11, price: 10 },
          ],
          notes: ["Somente folhas tamanho A3.", "Apenas para uso interno."],
        },
        {
          id: "adesivo-vinil-laser-com-semicorte",
          label: "Adesivo vinil com impressao laser - semicorte",
          pricingModel: "sheet_tiers",
          tiers: [
            { exact: 1, price: 25 },
            { min: 2, upTo: 5, price: 20 },
            { min: 5, upTo: 10, price: 15 },
            { min: 11, price: 13 },
          ],
          notes: ["Somente folhas tamanho A3.", "Apenas para uso interno."],
        },
      ],
    },
    {
      id: "plastificacao",
      label: "Plastificacao e acabamentos",
      status: "ready",
      products: [
        {
          id: "plastificacao-a4-sem-acabamento",
          label: "Plastificacao tamanho A4",
          pricingModel: "unit_tiers",
          tiers: [
            { min: 1, upTo: 10, price: 4.65 },
            { min: 11, upTo: 50, price: 4.1 },
            { min: 51, upTo: 100, price: 3.85 },
            { min: 100, price: 3.7 },
          ],
          notes: ["Sem corte ou acabamentos."],
          canCombineWith: ["copias-e-coloridos", "offset-folha"],
        },
        {
          id: "plastificacao-a4-com-acabamento",
          label: "Plastificacao A4 com acabamento",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "tamanho A4", price: 14 },
            { description: "02 por folha", price: 8 },
            { description: "04 por folha", price: 10 },
            { description: "06 por folha", price: 12 },
          ],
          canCombineWith: ["copias-e-coloridos", "offset-folha"],
        },
        {
          id: "plastificacao-a5",
          label: "Plastificacao tamanho A5",
          pricingModel: "fixed",
          unit: "un",
          price: 4.1,
        },
        {
          id: "plastificacao-rg",
          label: "Plastificacao tamanho RG",
          pricingModel: "fixed",
          unit: "un",
          price: 3.1,
        },
        {
          id: "plastificacao-a3-sem-acabamento",
          label: "Plastificacao tamanho A3",
          pricingModel: "unit_tiers",
          tiers: [
            { min: 1, upTo: 5, price: 10.4 },
            { min: 6, upTo: 50, price: 8.7 },
            { min: 51, price: 8.1 },
          ],
          notes: ["Sem corte ou acabamentos."],
        },
        {
          id: "plastificacao-a3-com-acabamento",
          label: "Plastificacao tamanho A3 com corte ou acabamento",
          pricingModel: "fixed",
          unit: "un",
          price: 23,
        },
      ],
    },
    {
      id: "encadernacoes",
      label: "Encadernacoes",
      status: "partial",
      products: [
        {
          id: "encadernacao-espiral",
          label: "Encadernacao espiral",
          pricingModel: "custom-table",
          notes: [
            "Tabela possui varias faixas por quantidade de folhas e quantidade de exemplares.",
            "Somente perfuracao: R$ 1,30.",
            "Vender somente capa (cada): R$ 1,55.",
            "Descontar da encadernacao (o par): R$ 1,50.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "encadernacao-termica",
          label: "Encadernacao termica",
          pricingModel: "custom-table",
          notes: [
            "1 encadernacao ate 200 folhas: R$ 14,00.",
            "Acima de 40 encadernacoes ate 200 folhas: R$ 13,20.",
            "Acima de 100 encadernacoes ate 200 folhas: R$ 11,90.",
            "1 encadernacao ate 500 folhas: R$ 22,00.",
            "Acima de 500 folhas: R$ 34,10.",
          ],
        },
        {
          id: "encadernacao-wire-o",
          label: "Encadernacao wire-o",
          pricingModel: "custom-table",
          notes: [
            "1 encadernacao ate 100 folhas: R$ 13,10.",
            "Acima de 10 encadernacoes ate 100 folhas: R$ 11,50.",
            "101 a 150 folhas: R$ 18,00.",
            "151 a 250 folhas: R$ 26,40.",
          ],
        },
        {
          id: "encadernacao-capa-mole-colorida",
          label: "Encadernacao capa mole colorida (brochura)",
          pricingModel: "custom-table",
          notes: [
            "1 encadernacao impressao maior que A3: R$ 38,50.",
            "Acima de 5 encadernacoes impressao maior que A3: R$ 30,25.",
            "1 encadernacao impressao tamanho A3: R$ 36,90.",
            "Acima de 5 encadernacoes impressao tamanho A3: R$ 29,70.",
            "1 encadernacao impressao tamanho A4: R$ 30,25.",
            "Acima de 5 encadernacoes impressao tamanho A4: R$ 24,80.",
          ],
        },
      ],
    },
    {
      id: "criacao",
      label: "Criacao",
      status: "ready",
      products: [
        {
          id: "etiquetas-simples-digitacao",
          label: "Etiquetas simples somente texto",
          pricingModel: "starting_at",
          unit: "servico",
          price: 20,
          notes: ["Digitacao.", "Minimo de impressao: 5 folhas papel adesivo ou 10 folhas papel couche."],
        },
        {
          id: "arte-completa",
          label: "Arte completa",
          pricingModel: "starting_at",
          unit: "servico",
          price: 75,
          notes: ["Minimo de impressao: 5 folhas papel adesivo ou 10 folhas papel couche."],
        },
        {
          id: "arte-blocos-comandas-pb",
          label: "Arte blocos ou comandas P/B",
          pricingModel: "starting_at",
          unit: "servico",
          price: 45,
          notes: ["Minimo de impressao: 300 folhas."],
        },
        {
          id: "arte-cartao-visita",
          label: "Arte para cartao de visita",
          pricingModel: "starting_at",
          unit: "servico",
          price: 75,
          notes: ["Minimo 100 cartoes.", "Arte com varias logomarcas pode ter acrescimo por dificuldade."],
        },
        {
          id: "arte-convites-lembrancas",
          label: "Arte para convites ou lembrancas",
          pricingModel: "starting_at",
          unit: "servico",
          price: 75,
          notes: ["Minimo 10 folhas ou R$ 20,00 do valor da impressao.", "Somente arte: R$ 280,00."],
        },
        {
          id: "arte-panfleto-sem-dobra-4x0",
          label: "Arte para panfletos sem dobra 4x0",
          pricingModel: "starting_at",
          unit: "servico",
          price: 75,
          notes: ["Minimo 10 folhas ou R$ 20,00 do valor da impressao.", "Somente arte: R$ 315,00."],
        },
        {
          id: "arte-panfleto-sem-dobra-4x4",
          label: "Arte para panfletos sem dobra 4x4",
          pricingModel: "starting_at",
          unit: "servico",
          price: 110,
          notes: ["Minimo 10 folhas ou R$ 20,00 do valor da impressao.", "Somente arte: R$ 315,00."],
        },
        {
          id: "arte-panfleto-a4-com-dobra",
          label: "Arte para panfletos A4 com dobra",
          pricingModel: "starting_at",
          unit: "servico",
          price: 110,
          notes: ["Minimo 10 folhas ou R$ 40,00 do valor da impressao.", "Somente arte: R$ 390,00."],
        },
        {
          id: "criacao-logomarca",
          label: "Criacao de logomarca",
          pricingModel: "starting_at",
          unit: "servico",
          price: 780,
        },
        {
          id: "hora-arte",
          label: "Hora arte",
          pricingModel: "fixed",
          unit: "hora",
          price: 110,
        },
      ],
    },
    {
      id: "scanners",
      label: "Scanners",
      status: "ready",
      products: [
        {
          id: "scanner-padrao",
          label: "Scanner padrao",
          pricingModel: "unit_tiers",
          tiers: [
            { exact: 1, totalPrice: 2 },
            { exact: 2, totalPrice: 3 },
            { min: 3, upTo: 5, price: 1 },
            { min: 6, upTo: 10, price: 0.6 },
            { min: 11, upTo: 50, price: 0.3 },
            { min: 51, upTo: 99, price: 0.2 },
            { min: 100, price: 0.18 },
          ],
        },
        {
          id: "scanner-folhas-soltas-advance",
          label: "Scanner folhas soltas advance",
          pricingModel: "unit_tiers",
          tiers: [
            { min: 1, upTo: 50, price: 0.2 },
            { min: 51, upTo: 100, price: 0.17 },
            { min: 101, upTo: 200, price: 0.15 },
            { min: 201, upTo: 500, price: 0.12 },
            { min: 500, price: 0.1 },
          ],
        },
        {
          id: "envio-email-scan",
          label: "Envio por email",
          pricingModel: "fixed",
          unit: "email",
          price: 5,
        },
        {
          id: "envio-whatsapp-scan",
          label: "Envio por WhatsApp",
          pricingModel: "fixed",
          unit: "envio",
          price: 0,
        },
      ],
    },
    {
      id: "banners-e-fotos",
      label: "Banners, fly banner e fotos",
      status: "ready",
      products: [
        {
          id: "fly-banner-3x075-base-concreto",
          label: "Fly banner 3x0,75 m completo com base de concreto",
          pricingModel: "fixed",
          unit: "un",
          price: 190,
          notes: ["Impressao dos dois lados.", "Prazo de producao: ate 10 dias."],
        },
        {
          id: "fly-banner-3x075-base-plastico",
          label: "Fly banner 3x0,75 m completo com base de plastico",
          pricingModel: "fixed",
          unit: "un",
          price: 170,
        },
        {
          id: "fly-banner-2x075-base-concreto",
          label: "Fly banner 2x0,75 m completo com base de concreto",
          pricingModel: "fixed",
          unit: "un",
          price: 205,
        },
        {
          id: "fly-banner-2x075-base-plastico",
          label: "Fly banner 2x0,75 m completo com base de plastico",
          pricingModel: "fixed",
          unit: "un",
          price: 190,
        },
        {
          id: "fly-banner-base-concreto",
          label: "Base de concreto para fly banner",
          pricingModel: "fixed",
          unit: "un",
          price: 30,
        },
        {
          id: "fly-banner-base-plastico",
          label: "Base de plastico para fly banner",
          pricingModel: "fixed",
          unit: "un",
          price: 25,
        },
        {
          id: "fly-banner-ferro",
          label: "Ferro para fly banner",
          pricingModel: "fixed",
          unit: "un",
          price: 66,
        },
        {
          id: "fly-banner-so-tecido-3x075",
          label: "So tecido fly banner 3x0,75 m",
          pricingModel: "fixed",
          unit: "un",
          price: 130,
        },
        {
          id: "fly-banner-so-tecido-2x075",
          label: "So tecido fly banner 2x0,75 m",
          pricingModel: "fixed",
          unit: "un",
          price: 160,
        },
        {
          id: "fly-banner-base-plastico-extra",
          label: "Base de plastico avulsa",
          pricingModel: "fixed",
          unit: "un",
          price: 55,
        },
        {
          id: "banner-glossy-paper",
          label: "Banner glossy paper",
          pricingModel: "mixed_sizes_and_linear",
          options: [
            { description: "35x50 cm", price: 35 },
            { description: "40x60 cm", price: 40 },
            { description: "60x90 cm", price: 58 },
            { description: "70x100 cm", price: 65 },
            { description: "80x120 cm", price: 75 },
            { description: "metro linear (largura 1,24 m)", price: 90 },
          ],
          notes: ["Minimo 35 cm."],
        },
        {
          id: "foto-glossy-10x15",
          label: "Foto 10x15 cm glossy paper",
          pricingModel: "unit_tiers",
          tiers: [
            { min: 50, upTo: 80, price: 1.43 },
            { min: 81, upTo: 100, price: 1.25 },
            { min: 101, upTo: 200, price: 1.17 },
            { min: 200, price: 1.15 },
          ],
          notes: ["Minimo 50 fotos.", "Pode ter diferenca de qualidade em relacao a revelacao digital."],
        },
      ],
    },
    {
      id: "carimbos-e-crachas",
      label: "Carimbos e crachas",
      status: "partial",
      products: [
        {
          id: "carimbo-madeira",
          label: "Carimbos de madeira",
          pricingModel: "fixed_variants",
          options: [
            { description: "Area 65x40 mm", price: 21.5 },
            { description: "Area 70x25 mm", price: 21.5 },
            { description: "Area 75x15 mm", price: 20 },
            { description: "Area 70x6 mm", price: 20 },
            { description: "Area 50x20 mm", price: 17.5 },
            { description: "Area 50x15 mm", price: 17.5 },
            { description: "Area 30x6 mm", price: 16.5 },
          ],
        },
        {
          id: "carimbo-redondo-madeira",
          label: "Carimbos redondos",
          pricingModel: "fixed_variants",
          options: [
            { description: "15 mm", price: 19 },
            { description: "20 mm", price: 19 },
            { description: "30 mm", price: 20 },
            { description: "35 mm", price: 20 },
            { description: "45 mm", price: 23 },
            { description: "50 mm", price: 23 },
            { description: "55 mm", price: 23 },
          ],
        },
        {
          id: "carimbo-pelicula",
          label: "So pelicula",
          pricingModel: "fixed",
          unit: "un",
          price: 3.5,
        },
        {
          id: "almofada-carimbo",
          label: "Almofada",
          pricingModel: "fixed",
          unit: "un",
          price: 21,
        },
        {
          id: "tinta-carimbo",
          label: "Tinta",
          pricingModel: "fixed",
          unit: "un",
          price: 16,
        },
        {
          id: "carimbo-automatico",
          label: "Carimbos automaticos",
          pricingModel: "fixed_variants",
          options: [
            { description: "P10 area 10x27 mm", price: 39.9, notes: ["Almofada R$ 15,00"] },
            { description: "P20 area 38x14 mm", price: 40, notes: ["Almofada R$ 16,00"] },
            { description: "P30 area 47x18 mm", price: 45, notes: ["Almofada R$ 17,00"] },
            { description: "P40 area 58x22 mm", price: 49, notes: ["Almofada R$ 18,00"] },
            { description: "P15 area 69x10 mm", price: 63, notes: ["Almofada R$ 19,50"] },
            { description: "P25 area 75x15 mm", price: 63, notes: ["Almofada R$ 19,50"] },
            { description: "P60 area 60x40 mm", price: 83.6, notes: ["Almofada R$ 24,00"] },
            { description: "P50 area 75x37 mm", price: 83.6, notes: ["Almofada R$ 24,00"] },
            { description: "P70 area 76x37 mm", price: 83.6, notes: ["Almofada R$ 24,00"] },
          ],
        },
        {
          id: "cracha-speed",
          label: "Cracha em speed",
          pricingModel: "sheet_tiers",
          tiers: [
            { min: 1, upTo: 4, price: 47.2 },
            { min: 5, upTo: 9, price: 39.95 },
            { min: 10, upTo: 19, price: 35.1 },
            { min: 20, price: 30.25 },
          ],
          notes: ["Tamanho 5,5 x 8,5 cm.", "Referencia por folha A4."],
        },
        {
          id: "cordao-credencial",
          label: "Cordao para credencial",
          pricingModel: "fixed",
          unit: "un",
          price: 0.75,
        },
        {
          id: "cordao-20mm-estampado",
          label: "Cordao 20 mm com estampa",
          pricingModel: "unit_tiers",
          tiers: [
            { exact: 10, price: 8 },
            { exact: 20, price: 6.5 },
            { exact: 30, price: 5 },
            { exact: 50, price: 4 },
          ],
        },
        {
          id: "cracha-pvc",
          label: "Cracha em PVC",
          pricingModel: "custom-table",
          notes: ["Tabela 4x0, 4x1 e 4x4 visivel no print, mas precisa de conferencia fina antes de integrar ao calculo automatico."],
          requiresManualTranscription: true,
        },
        {
          id: "cordao-sem-estampa",
          label: "Cordao sem estampa",
          pricingModel: "fixed",
          unit: "un",
          price: 2.75,
        },
        {
          id: "porta-cracha",
          label: "Porta cracha",
          pricingModel: "fixed",
          unit: "un",
          price: 2.75,
        },
        {
          id: "jacare-cracha",
          label: "Jacare",
          pricingModel: "fixed",
          unit: "un",
          price: 0.55,
        },
      ],
    },
    {
      id: "panfletos-e-folders",
      label: "Panfletos, folders e impressos especiais",
      status: "partial",
      products: [
        {
          id: "panfletos-couche-120g-laser",
          label: "Panfletos papel couché 120g - laser",
          pricingModel: "custom-table",
          notes: [
            "Tamanhos no print: 10x7 cm, 10x14 cm, 20x14 cm, 9,5x20 cm e 20x29 cm.",
            "Faixas por quantidade com variantes 4x0 e 4x4. Ex.: 10x7 cm 500 un 4x0 R$ 131,00 e 4x4 R$ 261,00.",
            "Observação do material: para frente e verso não poderá ser chapado.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "folder-couche-90g",
          label: "Folder couché 90g",
          pricingModel: "custom-table",
          notes: [
            "Tamanhos no print: 10x14 cm, 14x20 cm, 20x28 cm e 28x40 cm.",
            "Faixas principais: 2.500, 5.000 e 10.000 unidades em 4x0 e 4x4 conforme tamanho.",
            "Prazo destacado no material: 10 dias úteis.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "folder-couche-115g",
          label: "Folder couché 115g",
          pricingModel: "custom-table",
          notes: [
            "Tamanhos no print: 10x15 cm, 15x20 cm, 20x30 cm e 30x40 cm.",
            "Faixas principais: 2.500, 5.000 e 10.000 unidades em 4x0 e 4x4 conforme tamanho.",
            "Prazo destacado no material: 10 dias úteis.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "folder-couche-150g",
          label: "Folder couché 150g",
          pricingModel: "custom-table",
          notes: [
            "Tamanhos no print: 10x15 cm, 15x21 cm e 20x29,7 cm.",
            "Faixas principais: 2.500, 5.000 e 10.000 unidades em 4x0 e 4x4 conforme tamanho.",
            "Prazo destacado no material: 10 dias úteis.",
          ],
          requiresManualTranscription: true,
        },
      ],
    },
    {
      id: "panfletos-riso",
      label: "Panfletos riso",
      status: "partial",
      products: [
        {
          id: "panfletos-papel-75g-riso",
          label: "Panfletos papel 75g riso",
          pricingModel: "custom-table",
          notes: [
            "Tamanhos no print: 10x7 cm, 10x14 cm e 20x14 cm.",
            "Faixas por quantidade com variantes 4x0 e 4x4.",
            "Nesta fase, trate este grupo como referência de jato de tinta.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "panfletos-offset-120g-riso",
          label: "Panfletos papel offset 120g riso",
          pricingModel: "custom-table",
          notes: [
            "Tamanhos no print: 10x7 cm, 10x14 cm e 20x14 cm.",
            "Faixas por quantidade com variantes 4x0 e 4x4.",
            "Nesta fase, trate este grupo como referência de jato de tinta.",
          ],
          requiresManualTranscription: true,
        },
      ],
    },
    {
      id: "filipetas-e-postais",
      label: "Filipetas e postais",
      status: "partial",
      products: [
        {
          id: "filipeta-couche-115g",
          label: "Filipetas couché 115g",
          pricingModel: "fixed_variants",
          options: [
            { description: "2.500 un | 10x20 cm | 4x0", price: 440 },
            { description: "2.500 un | 10x20 cm | 4x4", price: 531 },
            { description: "5.000 un | 10x20 cm | 4x0", price: 697 },
            { description: "5.000 un | 10x20 cm | 4x4", price: 784 },
          ],
          notes: ["Prazo destacado no material: 10 dias úteis."],
        },
        {
          id: "filipeta-couche-150g",
          label: "Filipetas couché 150g",
          pricingModel: "fixed_variants",
          options: [
            { description: "2.500 un | 10,5x21 cm | 4x0", price: 796 },
            { description: "2.500 un | 10,5x21 cm | 4x4", price: 808 },
            { description: "5.000 un | 10,5x21 cm | 4x0", price: 1475 },
            { description: "5.000 un | 10,5x21 cm | 4x4", price: 1497 },
          ],
          notes: ["Prazo destacado no material: 10 dias úteis."],
        },
        {
          id: "postais-duplos",
          label: "Postais duplos",
          pricingModel: "custom-table",
          notes: [
            "Offset 300g verniz total frente 9x10 cm: 500 un 4x0 R$ 230,00 | 4x1 R$ 238,00 | 4x4 R$ 295,00; 1000 un 4x0 R$ 246,00 | 4x1 R$ 254,00 | 4x4 R$ 305,00.",
            "Verniz localizado 9x10 cm: 500 un 4x4 R$ 389,00 | 1000 un 4x4 R$ 480,00.",
            "Prazo: 10 dias úteis no verniz total e 12 dias úteis no verniz localizado.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "postais-triplos",
          label: "Postais triplos",
          pricingModel: "custom-table",
          notes: [
            "Offset 300g verniz total frente 9x15 cm: 500 un 4x0 R$ 351,00 | 4x4 R$ 327,00; 1000 un 4x0 R$ 303,00 | 4x4 R$ 387,00.",
            "Verniz localizado 9x15 cm: 500 un 4x4 R$ 500,00 | 1000 un 4x4 R$ 636,00.",
            "Prazo: 10 dias úteis no verniz total e 12 dias úteis no verniz localizado.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "postais-quadruplos",
          label: "Postais quádruplos",
          pricingModel: "custom-table",
          notes: [
            "Offset 300g laminado 10x18 cm: 500 un 4x0 R$ 339,00 | 4x4 R$ 357,00; 1000 un 4x0 R$ 377,00 | 4x4 R$ 525,00.",
            "Verniz localizado 10x18 cm: 500 un 4x4 R$ 775,00 | 1000 un 4x4 R$ 750,00.",
            "Prazo: 10 dias úteis no laminado e 12 dias úteis no verniz localizado.",
          ],
          requiresManualTranscription: true,
        },
      ],
    },
    {
      id: "acabamento-grafico",
      label: "Acabamento gráfico",
      status: "ready",
      products: [
        {
          id: "corte-com-estilete",
          label: "Corte com estilete",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "acima de 8 por folha", price: 2 },
            { description: "acima de 12 por folha (cada)", price: 2.5 },
            { description: "acima de 20 por folha (cada)", price: 3 },
            { description: "acima de 50 por folha (cada)", price: 10 },
          ],
        },
        {
          id: "livreto-acabamento",
          label: "Livreto",
          pricingModel: "unit_tiers",
          tiers: [
            { min: 1, upTo: 10, price: 2 },
            { min: 10, upTo: 20, price: 1.5 },
            { min: 21, price: 0.5 },
          ],
        },
        {
          id: "acabamentos-terceirizados",
          label: "Acabamentos sem produção na empresa",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "corte guilhotina por corte", price: 3 },
            { description: "colagem a partir de cada 500 folhas", price: 20 },
            { description: "picote até 3 linhas cada 1000 folhas", price: 20 },
          ],
        },
        {
          id: "acabamentos-internos",
          label: "Acabamentos com produção na empresa",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "corte guilhotina por corte", price: 1.5 },
            { description: "colagem a partir de cada 500 folhas", price: 15 },
            { description: "picote até 3 linhas cada 1000 folhas", price: 13 },
            { description: "corte mínimo na guilhotina", price: 4 },
          ],
        },
        {
          id: "furo-4-a-6mm",
          label: "Furo 4 a 6 mm",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "mínimo", price: 10 },
            { description: "cada cento", price: 3 },
            { description: "milheiro", price: 25 },
          ],
        },
        {
          id: "dobra-de-panfletos-1",
          label: "Dobra de panfletos - 1 dobra",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "mínimo", price: 10 },
            { description: "cada cento", price: 5 },
            { description: "milheiro", price: 50 },
          ],
        },
        {
          id: "dobra-de-panfletos-2",
          label: "Dobra de panfletos - 2 dobras",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "mínimo", price: 20 },
            { description: "cada cento", price: 10 },
            { description: "milheiro", price: 100 },
          ],
        },
      ],
    },
    {
      id: "corte-laser",
      label: "Corte laser",
      status: "ready",
      products: [
        {
          id: "ps-1mm-adesivo-corte-laser",
          label: "PS 1mm com adesivo com corte",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 45,
          tiers: [
            { upTo: 1, price: 186 },
            { min: 1, upTo: 2, price: 174 },
            { min: 2, upTo: 4, price: 162 },
            { min: 4, upTo: 10, price: 156 },
            { min: 10, price: 154 },
          ],
          canCombineWith: ["acabamentos-m2", "criacao"],
        },
        {
          id: "ps-2mm-adesivo-corte-laser",
          label: "PS 2mm com adesivo com corte",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 45,
          tiers: [
            { upTo: 1, price: 220 },
            { min: 1, upTo: 2, price: 204 },
            { min: 2, upTo: 4, price: 198 },
            { min: 4, upTo: 10, price: 192 },
            { min: 10, price: 188 },
          ],
          canCombineWith: ["acabamentos-m2", "criacao"],
        },
      ],
    },
    {
      id: "displays-e-cavaletes",
      label: "Displays e cavaletes",
      status: "partial",
      products: [
        {
          id: "cavalete-madeira-com-lona",
          label: "Cavalete de madeira com lona",
          pricingModel: "custom-table",
          notes: [
            "Prazo de produção: 3 dias úteis.",
            "Tamanhos visíveis no print: 0,6x0,9 m, 0,8x1,2 m, 1x0,9 m e 1,4x1 m com lona.",
            "Valores visíveis: R$ 145,00 | R$ 180,00 | R$ 240,00 | R$ 301,00.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "cavalete-metal-com-lona",
          label: "Cavalete de metal com lona",
          pricingModel: "fixed_variants",
          options: [
            { description: "0,6x0,9 m com lona", price: 234 },
            { description: "1x0,8 m com lona", price: 328.9 },
            { description: "1,2x0,9 m com lona", price: 392.6 },
            { description: "1,4x1 m com lona", price: 500 },
          ],
        },
      ],
    },
    {
      id: "camisetas-e-brindes",
      label: "Camisetas, canecas e brindes",
      status: "partial",
      products: [
        {
          id: "camisetas-basicas-sublimacao",
          label: "Camisetas básicas - sublimação 100% poliéster",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "01 unidade", price: 40 },
            { description: "02 unidades (cada)", price: 35 },
            { description: "a partir de 5 unidades (cada)", price: 34 },
          ],
          notes: ["Com 1 estampa tamanho A3.", "Estampa extra R$ 5,00 a unidade."],
        },
        {
          id: "somente-estampa-camiseta-basica",
          label: "Somente estampa camiseta básica",
          pricingModel: "fixed_variants",
          options: [
            { description: "A4 só frente", price: 7.5 },
            { description: "A4 frente e verso", price: 15 },
          ],
        },
        {
          id: "camisetas-dtf-textil",
          label: "Camisetas DTF têxtil",
          pricingModel: "custom-table",
          notes: [
            "Camiseta algodão: 1 un R$ 60,00 | 2 un R$ 55,00 cada | a partir de 5 un R$ 50,00 cada.",
            "Camiseta poliéster: 1 un R$ 55,00 | 2 un R$ 48,00 cada | a partir de 5 un R$ 40,00 cada.",
            "Com 1 estampa tamanho A3. Estampa extra: A4 R$ 5,00 | A3 R$ 10,00.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "caneca-ceramica",
          label: "Caneca de cerâmica",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "01 unidade", price: 35 },
            { description: "02 unidades (cada)", price: 27.5 },
          ],
          notes: ["Arte a partir de R$ 35,00. No material consta que a arte será cobrada apenas no primeiro pedido."],
        },
        {
          id: "caneca-aluminio",
          label: "Caneca de alumínio",
          pricingModel: "custom-table",
          notes: ["As faixas de valor não ficaram legíveis no print e precisam de conferência fina."],
          requiresManualTranscription: true,
        },
        {
          id: "caneca-plastico",
          label: "Caneca de plástico",
          pricingModel: "custom-table",
          notes: ["As faixas de valor não ficaram legíveis no print e precisam de conferência fina."],
          requiresManualTranscription: true,
        },
      ],
    },
    {
      id: "sublimacao-e-transfer",
      label: "Sublimação e transfer",
      status: "partial",
      products: [
        {
          id: "tecido-sublimacao-nosso-tecido",
          label: "Tecido sublimação - nosso tecido",
          pricingModel: "custom-table",
          notes: [
            "Valor mínimo destacado no material.",
            "Metro linear largura 1,5 m: R$ 71,50.",
            "Acima de 3 metros lineares: R$ 60,50. Os valores no print indicam que não incluem acabamento.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "somente-transfer-sem-aplicacao",
          label: "Somente transfer (sem aplicação)",
          pricingModel: "linear_meter_with_minimum",
          unit: "m",
          minimumReference: "50 cm",
          price: 25,
          notes: ["Largura 1,5 m.", "Sem aplicação."],
        },
        {
          id: "sublimacao-tecido-do-cliente-a3",
          label: "Sublimação tecido do cliente - folhas A3",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "1 folha A3", price: 15 },
            { description: "de 2 a 3 folhas A3", price: 7 },
            { description: "de 3 a 10 folhas A3", price: 5 },
            { description: "acima de 10 folhas A3", price: 4 },
          ],
        },
        {
          id: "sublimacao-tecido-do-cliente-1x15",
          label: "Sublimação tecido do cliente - folha 1x1,5 m",
          pricingModel: "fixed",
          unit: "folha",
          price: 55,
        },
      ],
    },
    {
      id: "adesivos-especiais-m2",
      label: "Adesivos especiais em m²",
      status: "ready",
      products: [
        {
          id: "adesivo-holografico-ecossolvente",
          label: "Adesivo holográfico - impressão ecosolvente",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 40,
          tiers: [
            { upTo: 1, price: 140 },
            { min: 1, upTo: 3, price: 130 },
            { min: 3, price: 120 },
          ],
          notes: ["Prazo de produção até 3 dias úteis."],
          canCombineWith: ["acabamentos-m2", "criacao"],
        },
        {
          id: "adesivo-holografico-uv",
          label: "Adesivo holográfico - impressão UV",
          pricingModel: "area_tiers_with_minimum",
          unit: "m2",
          minimumCharge: 50,
          tiers: [
            { upTo: 1, price: 200 },
            { min: 1, upTo: 3, price: 180 },
            { min: 3, price: 170 },
          ],
          notes: ["Prazo de produção até 5 dias úteis."],
          canCombineWith: ["acabamentos-m2", "criacao"],
        },
      ],
    },
    {
      id: "adesivos-especiais-folha",
      label: "Adesivos especiais por folha",
      status: "ready",
      products: [
        {
          id: "adesivo-resinado-vinil-branco-ou-transparente",
          label: "Adesivo resinado - vinil branco ou transparente",
          pricingModel: "fixed_brackets",
          unit: "folha-a3",
          brackets: [
            { description: "1 folha A3", price: 50 },
            { description: "2 folhas A3 (a unidade)", price: 45 },
            { description: "5 folhas A3 (a unidade)", price: 40 },
            { description: "10 folhas A3 (a unidade)", price: 38 },
          ],
          notes: ["Prazo de produção até 10 dias.", "Espaço entre cada adesivo: 3 mm.", "Somente formas geométricas."],
        },
        {
          id: "adesivo-resinado-vinil-especial",
          label: "Adesivo resinado - vinil especial",
          pricingModel: "fixed_brackets",
          unit: "folha-a3",
          brackets: [
            { description: "1 folha A3", price: 70 },
            { description: "2 folhas A3 (a unidade)", price: 65 },
            { description: "5 folhas A3 (a unidade)", price: 60 },
            { description: "10 folhas A3 (a unidade)", price: 55 },
          ],
          notes: ["Metálicos, holográfico, entre outros.", "Prazo de produção até 10 dias.", "Espaço entre cada adesivo: 3 mm.", "Somente formas geométricas."],
        },
      ],
    },
    {
      id: "chaveiros-e-brindes",
      label: "Chaveiros e brindes",
      status: "ready",
      products: [
        {
          id: "chaveiro-caminhao",
          label: "Chaveiro caminhão",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 65 },
            { description: "20 unidades", price: 115 },
            { description: "50 unidades", price: 250 },
            { description: "100 unidades", price: 470 },
          ],
          notes: ["Tamanho do chaveiro: 167x23 mm.", "Área personalizável: 27x13 mm."],
        },
        {
          id: "chaveiro-mosquetao-1-lado",
          label: "Chaveiro mosquetão - propaganda 1 lado",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 40 },
            { description: "20 unidades", price: 70 },
            { description: "50 unidades", price: 150 },
            { description: "100 unidades", price: 230 },
          ],
          notes: ["Tamanho do chaveiro: 61x31 mm.", "Área personalizável: 22x16 mm."],
        },
        {
          id: "chaveiro-mosquetao-2-lados",
          label: "Chaveiro mosquetão - propaganda 2 lados",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 52 },
            { description: "20 unidades", price: 91 },
            { description: "50 unidades", price: 182 },
            { description: "100 unidades", price: 299 },
          ],
          notes: ["Tamanho do chaveiro: 61x31 mm.", "Área personalizável: 22x16 mm."],
        },
        {
          id: "chaveiro-mosquetao-abridor-1-lado",
          label: "Chaveiro mosquetão abridor de garrafa - propaganda 1 lado",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 65 },
            { description: "20 unidades", price: 115 },
            { description: "50 unidades", price: 250 },
            { description: "100 unidades", price: 470 },
          ],
          notes: ["Tamanho do chaveiro: 78x39 mm.", "Área personalizável: 29x9 mm."],
        },
        {
          id: "chaveiro-mosquetao-abridor-2-lados",
          label: "Chaveiro mosquetão abridor de garrafa - propaganda 2 lados",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 84.5 },
            { description: "20 unidades", price: 149.5 },
            { description: "50 unidades", price: 325 },
            { description: "100 unidades", price: 611 },
          ],
          notes: ["Tamanho do chaveiro: 78x39 mm.", "Área personalizável: 29x9 mm."],
        },
        {
          id: "chaveiro-bombona-lisa-1-lado",
          label: "Chaveiro bombona d'água lisa - propaganda 1 lado",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 40 },
            { description: "20 unidades", price: 70 },
            { description: "50 unidades", price: 150 },
            { description: "100 unidades", price: 230 },
          ],
          notes: ["Tamanho do chaveiro: 50x25 mm.", "Área personalizável: 24x35 mm."],
        },
        {
          id: "chaveiro-bombona-lisa-2-lados",
          label: "Chaveiro bombona d'água lisa - propaganda 2 lados",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 52 },
            { description: "20 unidades", price: 91 },
            { description: "50 unidades", price: 195 },
            { description: "100 unidades", price: 299 },
          ],
          notes: ["Tamanho do chaveiro: 50x25 mm.", "Área personalizável: 24x35 mm."],
        },
        {
          id: "chaveiro-bombona-relevo",
          label: "Chaveiro bombona com relevo",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 37 },
            { description: "20 unidades", price: 65 },
            { description: "50 unidades", price: 120 },
            { description: "100 unidades", price: 200 },
          ],
          notes: ["Tamanho do chaveiro: 40x18 mm.", "Área personalizável: 20x15 mm."],
        },
        {
          id: "chaveiro-botijao-liso-1-lado",
          label: "Chaveiro botijão de gás liso - propaganda 1 lado",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 40 },
            { description: "20 unidades", price: 70 },
            { description: "50 unidades", price: 150 },
            { description: "100 unidades", price: 230 },
          ],
          notes: ["Tamanho do chaveiro: 41x28 mm.", "Área personalizável: 26x34 mm."],
        },
        {
          id: "chaveiro-botijao-liso-2-lados",
          label: "Chaveiro botijão de gás liso - propaganda 2 lados",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 52 },
            { description: "20 unidades", price: 91 },
            { description: "50 unidades", price: 195 },
            { description: "100 unidades", price: 299 },
          ],
          notes: ["Tamanho do chaveiro: 41x28 mm.", "Área personalizável: 26x34 mm."],
        },
        {
          id: "chaveiro-botijao-relevo",
          label: "Chaveiro botijão de gás com relevo",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 40 },
            { description: "20 unidades", price: 70 },
            { description: "50 unidades", price: 150 },
            { description: "100 unidades", price: 230 },
          ],
          notes: ["Tamanho do chaveiro: 38x24 mm.", "Área personalizável: 21x16 mm."],
        },
        {
          id: "chaveiro-cortador-unha-com-abridor",
          label: "Chaveiro cortador de unha com abridor",
          pricingModel: "fixed_brackets",
          brackets: [
            { description: "10 unidades", price: 60 },
            { description: "20 unidades", price: 100 },
            { description: "50 unidades", price: 240 },
            { description: "100 unidades", price: 450 },
          ],
          notes: ["Tamanho do chaveiro: 60x33 mm.", "Área personalizável: 26x26 mm."],
        },
      ],
    },
    {
      id: "cartoes-de-visita",
      label: "Cartoes de visita",
      status: "partial",
      products: [
        {
          id: "cartao-offset-couche-250g",
          label: "Cartao de visita offset couché 250g 9x5 cm",
          pricingModel: "custom-table",
          notes: [
            "Tabela com 1000, 2000, 3000 e 5000 cartoes.",
            "Variantes: so frente, verso preto e verso colorido.",
            "Valores visibles no print e prontos para transcricao fina em proxima etapa.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "cartao-offset-couche-300g",
          label: "Cartao de visita offset couché 300g 9x5 cm",
          pricingModel: "custom-table",
          notes: [
            "Tabela com 1000, 2000, 3000 e 5000 cartoes.",
            "Variantes: so frente, verso preto e verso colorido.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "cartao-offset-supreme-300g",
          label: "Cartao de visita offset supreme 300g 9x5 cm",
          pricingModel: "custom-table",
          notes: [
            "Tabela com 1000, 2000, 3000 e 5000 cartoes.",
            "Variantes: so frente, verso preto e verso colorido.",
          ],
          requiresManualTranscription: true,
        },
        {
          id: "cartao-offset-verniz-localizado",
          label: "Cartao de visita offset verniz localizado 8,8 x 4,8 cm",
          pricingModel: "custom-table",
          notes: ["Faixas: 500, 1000, 2000, 3000 e 5000 cartoes 4x4.", "Cantos arredondados: acrescenta R$ 13,00 o milheiro."],
          requiresManualTranscription: true,
        },
        {
          id: "cartao-offset-reciclato-230g",
          label: "Cartao de visita offset reciclato 230g 9x5 cm",
          pricingModel: "fixed_variants",
          options: [
            { description: "1000 cartoes 4x0", price: 188 },
            { description: "1000 cartoes 4x4", price: 194 },
          ],
        },
        {
          id: "cartao-hot-stamping-lam-fosca",
          label: "Cartao de visita hot stamping + lam fosca 9x5 cm",
          pricingModel: "fixed_variants",
          options: [
            { description: "500 cartoes 4x0", price: 426 },
            { description: "500 cartoes 4x4", price: 481 },
            { description: "1000 cartoes 4x0", price: 603 },
            { description: "1000 cartoes 4x4", price: 654 },
          ],
          notes: ["Aplicacao do hot stamping somente em 1 dos lados.", "Cantos arredondados: acrescenta R$ 13,00 o milheiro."],
        },
        {
          id: "cartao-hot-stamping-uv-localizado",
          label: "Cartao de visita hot stamping + UV localizado 9x5 cm",
          pricingModel: "fixed_variants",
          options: [
            { description: "500 cartoes 4x0", price: 458 },
            { description: "500 cartoes 4x4", price: 515 },
            { description: "1000 cartoes 4x0", price: 726 },
            { description: "1000 cartoes 4x4", price: 775 },
          ],
          notes: [
            "Cores disponiveis do hot stamping: dourado, prata, azul, vermelho e rosa.",
            "Cantos arredondados: acrescenta R$ 13,00 o milheiro.",
          ],
        },
      ],
    },
  ],
  addonGroups: [
    {
      id: "acabamentos-m2",
      label: "Acabamentos para produtos em m2",
      options: [
        { id: "sem-acabamento", label: "Sem acabamento", pricingModel: "none" },
        { id: "ilhos-simples", label: "Ilhos simples", pricingModel: "unit", price: 0.9, unit: "un" },
        { id: "ilhos-latao", label: "Ilhos latao", pricingModel: "unit", price: 1.5, unit: "un" },
        { id: "bainha-com-corda", label: "Bainha com corda", pricingModel: "linear_meter", price: 5, unit: "m" },
        { id: "laminacao", label: "Laminacao", pricingModel: "area", price: 25, unit: "m2" },
        { id: "verniz-laka", label: "Verniz laka", pricingModel: "area", price: 5, unit: "m2" },
      ],
    },
  ],
};
